### ISSUE TITLE
Deletion script for resources created with deploy-tre script in Aws account

### ISSUE THREAD

**Issue by kaul-abhi** [aws-samples/service-catalog-engine-for-terraform-os#56]
Hello,
I can see that this repo uses AWS SAM and cloudformation to create bunch of stuff used for Terraform Reference Engine.
But my use case is when i have deployed the resources, how i can delete it. I can see that while using command "sam delete" it doesnt delete the cloudformation stack as s3 buckets created are not empty.
Kindly help or automate the deletion process also.

**Comment by smaly-amazon** [comment]
Hi,

Thanks for this feedback. Yes, as mentioned in #26 there are S3 buckets that need to be emptied before the SAM-TRE stack can be deleted. Also, the two stacks must be deleted in the correct order since they depend on a stack export.

We will look into adding a delete script and/or adding delete steps to the Readme.

**Comment by kaul-abhi** [comment]
Hello Team, any update on deletion script? i am facing the same issue where in logging bucket if there are more than 1000 objects then via aws cli buckets are not getting emptied.

**Comment by smaly-amazon** [comment]
Hi,

You can empty the buckets using the AWS S3 console. As mentioned above, we will consider adding a script to automate deletion.

Closing this in favor of a previous issue.
https://github.com/aws-samples/service-catalog-engine-for-terraform-os/issues/26
